/* ASO Companion - app-wide constants */

export const DAY_KEYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const
export type DayKey = (typeof DAY_KEYS)[number]

export const DAY_FULL: Record<string, string> = {
  Mon: 'Monday',
  Tue: 'Tuesday',
  Wed: 'Wednesday',
  Thu: 'Thursday',
  Fri: 'Friday',
  Sat: 'Saturday',
  Sun: 'Sunday',
}

export const SKILLS = [
  { k: 'L', name: 'Listening' },
  { k: 'S', name: 'Speaking' },
  { k: 'R', name: 'Reading' },
  { k: 'W', name: 'Writing' },
] as const

export const LIB_SKILLS = ['', 'L', 'S', 'R', 'W'] as const

/* Library groups in display order, organised by what a teacher needs: lessons
   first, then visuals, games, media, practice, reading, tests, teacher
   support and self-study last. */
export const LIB_GROUPS = [
  { k: 'courses', label: 'Coursebooks and lesson plans', hint: 'Ready-made lessons, units and coursebooks', match: ['lesson plan', 'lesson unit', 'coursebook', 'cambridge global', 'american english file', 'english file', 'spotlight'] },
  { k: 'visuals', label: 'Flashcards and visuals', hint: 'Picture sets, slides and seasonal packs', match: ['flashcard', 'powerpoint', 'seasonal'] },
  { k: 'games', label: 'Games and speaking activities', hint: 'Games, speaking cards and thinking tasks', match: ['game', 'speaking', 'critical'] },
  { k: 'media', label: 'Songs, video and audio', hint: 'Songs, videos, listening and podcasts', match: ['song', 'music', 'video', 'listening', 'podcast', 'audiobook'] },
  { k: 'worksheets', label: 'Worksheets and practice', hint: 'Printable practice, grammar and writing help', match: ['worksheet', 'kids english', 'comprehension', 'reading task', 'creative', 'writing', 'grammar', 'maths'] },
  { k: 'books', label: 'Books and reading', hint: 'Readers, books and reference libraries', match: ['book'] },
  { k: 'tests', label: 'Tests and exams', hint: 'Test banks, quizzes and exam preparation', match: ['test', 'quiz', 'ket', 'pet', 'ielts', 'ready for'] },
  { k: 'teacher', label: 'Teacher training and support', hint: 'Methodology, how-to guides and inclusive materials', match: ['teacher', 'how-to', 'autism'] },
  { k: 'selfstudy', label: 'Self-study and extras', hint: 'For students at home, business English and everything else', match: ['app', 'learn english', 'business', 'awesome', 'contribution', 'misc'] },
] as const

export function libGroup(l: { name: string; cat?: string }) {
  const byKey = LIB_GROUPS.find((g) => g.k === l.cat)
  if (byKey) return byKey
  const n = String(l.name || '').toLowerCase()
  for (const g of LIB_GROUPS) {
    if (g.match.some((kw) => n.indexOf(kw) > -1)) return g
  }
  return LIB_GROUPS[LIB_GROUPS.length - 1]
}

/* ---- 24h time options in 30-minute steps (for the time picker) ---- */
export const TIME_OPTIONS: string[] = (() => {
  const out: string[] = []
  for (let h = 6; h <= 23; h++) {
    out.push(`${String(h).padStart(2, '0')}:00`)
    out.push(`${String(h).padStart(2, '0')}:30`)
  }
  return out
})()

/* default level keys in canonical order */
export const LEVEL_ORDER = [
  'kids-beg',
  'kids-int',
  'kids-adv',
  'teens-beg',
  'teens-int',
  'teens-adv',
  'adults-beg',
  'adults-int',
  'adults-adv',
] as const

export const BANDS = ['Kids', 'Teens', 'Adults'] as const

/* canonical rooms/spaces offered in the room dropdowns (rooms already in use
   are added to the list dynamically - see roomOptionsFor) */
export const ROOM_OPTIONS = ['Room 1', 'Room 2', 'Room 3', 'Main Hall'] as const

/* small legend printed under the exports so readers know where each room is.
   ASO layout: the Library and Room 1 are on the ground floor; Room 2 and the
   Main Hall are upstairs. */
export const ROOM_LEGEND = 'Ground floor: Room 1 & Library · Upstairs: Room 2 & Main Hall'

/* ---- reporting guide ---- */
export const REPORT_SYSTEM_URL =
  'https://sites.google.com/view/espaceamericainoujda/accueil/teacher-volunteer-intern-trainer'

export const REPORT_STEPS = [
  { t: 'Sign in', d: 'Open the reporting site and login using your ASO number and password.' },
  { t: 'First Class Info', d: 'The first tab you should see. Fill in the details of your class: when your class starts, which student category and level, and the repetition · weekly, bi-weekly and so on.' },
  { t: 'Participants Management', d: 'The next tab. This is where you add all the ASO numbers of all your students. This is also where you put the marks.' },
  { t: 'Courses Taught', d: 'Register each new session every week here: your number, your full name, when the session happened and the number of attendees.' },
  { t: 'Attendance', d: 'Mark all the attendance during class · who came and who did not.' },
  { t: 'Reports', d: 'The final tab · your reports are there once the rest is filled in.' },
]

export const REPORT_EXAMPLE = `REF-cls-a3b7c1-2026-10-21-1400   <- auto-generated by the site, you never type it
Date: 2026-10-21 (Wednesday)
Time: 14:00 - 16:00
Topic: Kids · Beginners · Week 3 Colors
Speaker: Aya (ASO-K1, Room 1)
Total audience: 11   <- auto-filled from the session's "Number of attendees", locked
Type of activities: Class          (Meeting / Club / Event / Workshop / Class)
Type of categories: English Language Learning
                    (Information about the USA / English Language Learning / Education on the U.S.A. / Alumni Activities / Community Engagement)
Summary text:
Week 3 introduced the five colour words (red, blue, green, yellow, orange) and the frame "It is [colour].". Eleven learners were registered; nine attended (Imane and Yassine absent, recorded in Attendance). The lesson followed the standard 2-hour arc.

After the hello routine, a quick feelings review showed the class still holds four of the six feeling words from Week 2. The new colour vocabulary was presented with large flashcards and modelled in full sentences; most learners could produce "It is red" by the end of the guided practice slot. The listening task ("Listen and colour") gave an honest comprehension check: eight of the nine present matched every description correctly. After the break, the team collage brought the language together. Three teams cut magazine pictures in their colour and presented "It is blue!" to the class. Reading and writing closed the session with tracing and colouring of the five target words.

What worked: the team collage. Full sentences from every learner, real pride in the wall gallery, and the "It is [colour]" frame is now stable.
What to change: red and orange were confused by three learners (the crayon shades are too close). Next week, use larger and more distinct colour swatches, and pair each colour with a classroom object to keep the words recycling.
One concrete step for next week: link colours to classroom objects (the red chair, the blue pen) in Week 4 Numbers, so the colour words are reused in a new context.

Drafted by: Aya`

/* ---- lesson plan stage times ---- */
export const LP_STAGES_KIDS = {
  hello: '0:00-0:10',
  wu: '0:10-0:20',
  pres: '0:20-0:35',
  prac: '0:35-0:50',
  ls: '0:50-1:00',
  brk: '1:00-1:10',
  re: '1:10-1:20',
  prod: '1:20-1:45',
  rw: '1:45-1:55',
  st: '1:55-2:00',
} as const

export const LP_STAGES_TEENS = {
  hello: '0:00-0:05',
  wu: '0:05-0:15',
  pres: '0:15-0:35',
  prac: '0:35-0:55',
  ls: '0:55-1:05',
  brk: '1:05-1:15',
  re: '1:15-1:25',
  prod: '1:25-1:45',
  rw: '1:45-1:55',
  st: '1:55-2:00',
} as const

/* ---- local storage keys ---- */
export const LS_KEY = 'aso-companion-v1'
export const ROLE_KEY = 'aso-role' // 'admin' | 'pub'

/* lesson stage labels for the Drive kit attached to each week */
export const KIT_STAGE_LABELS: Record<string, string> = {
  wu: 'Warm-up',
  pres: 'Presentation',
  prac: 'Practice',
  ls: 'Listening',
  re: 'Reactivation game',
  prod: 'Production task',
  rw: 'Reading & writing',
  st: 'Story / song + goodbye',
}
