/* ASO Companion - app-wide constants */

export const DAY_KEYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as const
export type DayKey = (typeof DAY_KEYS)[number]

export const DAY_FULL: Record<string, string> = {
  Mon: 'Monday',
  Tue: 'Tuesday',
  Wed: 'Wednesday',
  Thu: 'Thursday',
  Fri: 'Friday',
  Sat: 'Saturday',
  Sun: 'Sunday',
}

export const SKILLS = [
  { k: 'L', name: 'Listening' },
  { k: 'S', name: 'Speaking' },
  { k: 'R', name: 'Reading' },
  { k: 'W', name: 'Writing' },
] as const

export const LIB_SKILLS = ['', 'L', 'S', 'R', 'W'] as const

/* Library categories in display order (importance): teacher resources first,
   then planning, coursebooks, exams, learner materials, media, reading,
   writing, speaking, and everything else last. */
export const LIB_CATEGORIES = [
  { k: 'teacher', label: 'Teacher resources', match: ['teacher', "teacher's guide"] },
  { k: 'planning', label: 'Planning', match: ['lesson plan', 'writing guide'] },
  { k: 'course', label: 'Coursebooks', match: ['coursebook', 'cambridge global', 'english books', 'ready for'] },
  { k: 'exams', label: 'Tests & exams', match: ['test', 'quiz', 'ket', 'pet', 'ielts'] },
  { k: 'learner', label: 'Learner materials', match: ['kids english', 'flashcard', 'worksheet', 'maths', 'autism', 'seasonal'] },
  { k: 'media', label: 'Listening & media', match: ['listening', 'podcast', 'audiobook', 'video', 'music', 'song'] },
  { k: 'reading', label: 'Reading', match: ['reading', 'comprehension', 'book'] },
  { k: 'writing', label: 'Writing', match: ['writing', 'creative'] },
  { k: 'speaking', label: 'Speaking & activities', match: ['speaking', 'game', 'powerpoint', 'critical'] },
  { k: 'other', label: 'Other', match: ['business', 'app', 'misc', 'contribution'] },
] as const

export function libCategory(name: string) {
  const n = String(name || '').toLowerCase()
  for (const c of LIB_CATEGORIES) {
    if (c.match.some((kw) => n.indexOf(kw) > -1)) return c
  }
  return LIB_CATEGORIES[LIB_CATEGORIES.length - 1] // Other
}

/* ---- 24h time options in 30-minute steps (for the time picker) ---- */
export const TIME_OPTIONS: string[] = (() => {
  const out: string[] = []
  for (let h = 6; h <= 23; h++) {
    out.push(`${String(h).padStart(2, '0')}:00`)
    out.push(`${String(h).padStart(2, '0')}:30`)
  }
  return out
})()

/* default level keys in canonical order */
export const LEVEL_ORDER = [
  'kids-beg',
  'kids-int',
  'kids-adv',
  'teens-beg',
  'teens-int',
  'teens-adv',
  'adults-beg',
  'adults-int',
  'adults-adv',
] as const

export const BANDS = ['Kids', 'Teens', 'Adults'] as const

/* ---- reporting guide ---- */
export const REPORT_SYSTEM_URL =
  'https://sites.google.com/view/espaceamericainoujda/accueil/teacher-volunteer-intern-trainer'

export const REPORT_STEPS = [
  { t: 'Sign in', d: 'Open the reporting site and login using your ASO number and password.' },
  { t: 'First Class Info', d: 'The first tab you should see. Fill in the details of your class: when your class starts, which student category and level, and the repetition · weekly, bi-weekly and so on.' },
  { t: 'Participants Management', d: 'The next tab. This is where you add all the ASO numbers of all your students. This is also where you put the marks.' },
  { t: 'Courses Taught', d: 'Register each new session every week here: your number, your full name, when the session happened and the number of attendees.' },
  { t: 'Attendance', d: 'Mark all the attendance during class · who came and who did not.' },
  { t: 'Reports', d: 'The final tab · your reports are there once the rest is filled in.' },
]

export const REPORT_EXAMPLE = `REF-cls-a3b7c1-2026-10-21-1400   <- auto-generated by the site, you never type it
Date: 2026-10-21 (Wednesday)
Time: 14:00 - 16:00
Topic: Kids · Beginners · Week 3 Colors
Speaker: Aya (ASO-K1, Room 1)
Total audience: 11   <- auto-filled from the session's "Number of attendees", locked
Type of activities: Class          (Meeting / Club / Event / Workshop / Class)
Type of categories: English Language Learning
                    (Information about the USA / English Language Learning / Education on the U.S.A. / Alumni Activities / Community Engagement)
Summary text:
Week 3 introduced the five colour words (red, blue, green, yellow, orange) and the frame "It is [colour].". Eleven learners were registered; nine attended (Imane and Yassine absent, recorded in Attendance). The lesson followed the standard 2-hour arc.

After the hello routine, a quick feelings review showed the class still holds four of the six feeling words from Week 2. The new colour vocabulary was presented with large flashcards and modelled in full sentences; most learners could produce "It is red" by the end of the guided practice slot. The listening task ("Listen and colour") gave an honest comprehension check: eight of the nine present matched every description correctly. After the break, the team collage brought the language together. Three teams cut magazine pictures in their colour and presented "It is blue!" to the class. Reading and writing closed the session with tracing and colouring of the five target words.

What worked: the team collage. Full sentences from every learner, real pride in the wall gallery, and the "It is [colour]" frame is now stable.
What to change: red and orange were confused by three learners (the crayon shades are too close). Next week, use larger and more distinct colour swatches, and pair each colour with a classroom object to keep the words recycling.
One concrete step for next week: link colours to classroom objects (the red chair, the blue pen) in Week 4 Numbers, so the colour words are reused in a new context.

Drafted by: Aya`

/* ---- lesson plan stage times ---- */
export const LP_STAGES_KIDS = {
  hello: '0:00-0:10',
  wu: '0:10-0:20',
  pres: '0:20-0:35',
  prac: '0:35-0:50',
  ls: '0:50-1:00',
  brk: '1:00-1:10',
  re: '1:10-1:20',
  prod: '1:20-1:45',
  rw: '1:45-1:55',
  st: '1:55-2:00',
} as const

export const LP_STAGES_TEENS = {
  hello: '0:00-0:05',
  wu: '0:05-0:15',
  pres: '0:15-0:30',
  prac: '0:30-0:45',
  ls: '0:45-0:55',
  brk: '0:55-1:00',
  re: '1:00-1:08',
  prod: '1:08-1:22',
  rw: '1:22-1:28',
  st: '1:28-1:30',
} as const

/* ---- local storage keys ---- */
export const LS_KEY = 'aso-companion-v1'
export const ROLE_KEY = 'aso-role' // 'admin' | 'pub'
