'use client'

import type { ElementType } from 'react'
import {
  Anchor,
  Apple,
  Atom,
  Award,
  Baby,
  Bike,
  Bird,
  BookMarked,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  Castle,
  Cat,
  Clapperboard,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cookie,
  Carrot,
  Croissant,
  Crown,
  Dices,
  Dna,
  Dog,
  Drama,
  Drum,
  Dumbbell,
  Feather,
  Film,
  Fish,
  Flag,
  FlaskConical,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Ghost,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Hand,
  Headphones,
  Heart,
  HeartHandshake,
  IceCreamCone,
  Joystick,
  Key,
  Landmark,
  Languages,
  Lamp,
  Laptop,
  Leaf,
  Lightbulb,
  Map,
  Medal,
  Megaphone,
  MessageCircle,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Palette,
  Palmtree,
  PenLine,
  Piano,
  Pizza,
  Plane,
  Podcast,
  Puzzle,
  Radio,
  Rabbit,
  Rainbow,
  Rocket,
  Ruler,
  Sailboat,
  Scissors,
  Ship,
  Shirt,
  Smile,
  Snowflake,
  Sparkle,
  Sparkles,
  Speaker,
  Sprout,
  Squirrel,
  Star,
  Sun,
  Swords,
  Target,
  Tent,
  TestTube,
  Telescope,
  TrainFront,
  TreePine,
  Trophy,
  Turtle,
  Umbrella,
  Users,
  UtensilsCrossed,
  Video,
  Wand2,
  Watch,
  Waves,
  Wind,
  Zap,
} from 'lucide-react'

export interface IconChoice {
  name: string
  label: string
  Icon: ElementType
}

/* Icon palette offered in the club / event editor. The chosen icon renders on
   the calendar chip in place of a plain dot. The first block keeps the
   original keys so existing clubs and events keep their icons. */
export const CLUB_ICONS: IconChoice[] = [
  /* original set */
  { name: 'chess', label: 'Chess', Icon: Crown },
  { name: 'music', label: 'Music', Icon: Music },
  { name: 'book', label: 'Book club', Icon: BookOpen },
  { name: 'film', label: 'Film', Icon: Film },
  { name: 'mic', label: 'Public speaking', Icon: Mic },
  { name: 'art', label: 'Art', Icon: Palette },
  { name: 'code', label: 'Coding', Icon: Code },
  { name: 'game', label: 'Games', Icon: Gamepad2 },
  { name: 'pen', label: 'Writing', Icon: PenLine },
  { name: 'star', label: 'Star', Icon: Star },
  { name: 'calendar', label: 'Calendar', Icon: Sparkles },
  { name: 'globe', label: 'Culture', Icon: Globe },
  { name: 'languages', label: 'Languages', Icon: Languages },
  { name: 'theater', label: 'Theater', Icon: Drama },
  { name: 'camera', label: 'Photography', Icon: Camera },
  { name: 'sport', label: 'Sport', Icon: Dumbbell },
  { name: 'science', label: 'Science', Icon: Lightbulb },
  { name: 'debate', label: 'Debate', Icon: MessageCircle },
  { name: 'environment', label: 'Environment', Icon: Leaf },
  { name: 'community', label: 'Community', Icon: Users },
  { name: 'food', label: 'Cooking', Icon: UtensilsCrossed },
  { name: 'tech', label: 'Tech', Icon: Laptop },
  { name: 'brain', label: 'Philo', Icon: Brain },
  { name: 'rocket', label: 'Space', Icon: Rocket },
  { name: 'heart', label: 'Wellness', Icon: Heart },
  { name: 'news', label: 'Journalism', Icon: Newspaper },
  { name: 'coffee', label: 'Café', Icon: Coffee },

  /* music & stage */
  { name: 'guitar', label: 'Guitar', Icon: Guitar },
  { name: 'piano', label: 'Piano', Icon: Piano },
  { name: 'drum', label: 'Drums', Icon: Drum },
  { name: 'headphones', label: 'Listening', Icon: Headphones },
  { name: 'podcast', label: 'Podcast', Icon: Podcast },
  { name: 'radio', label: 'Radio', Icon: Radio },
  { name: 'video', label: 'Video', Icon: Video },
  { name: 'cinema', label: 'Cinema', Icon: Clapperboard },
  { name: 'backstage', label: 'Backstage', Icon: Sparkle },

  /* arts & crafts */
  { name: 'brush', label: 'Painting', Icon: Brush },
  { name: 'craft', label: 'Crafts', Icon: Scissors },
  { name: 'fashion', label: 'Fashion', Icon: Shirt },
  { name: 'design', label: 'Design', Icon: Ruler },

  /* sport & movement */
  { name: 'trophy', label: 'Trophy', Icon: Trophy },
  { name: 'medal', label: 'Medals', Icon: Medal },
  { name: 'target', label: 'Archery', Icon: Target },
  { name: 'bike', label: 'Cycling', Icon: Bike },
  { name: 'swim', label: 'Swimming', Icon: Waves },
  { name: 'hike', label: 'Hiking', Icon: Mountain },
  { name: 'run', label: 'Running', Icon: Footprints },
  { name: 'energy', label: 'Energy', Icon: Zap },
  { name: 'martial', label: 'Martial arts', Icon: Swords },

  /* games & imagination */
  { name: 'dices', label: 'Board games', Icon: Dices },
  { name: 'puzzle', label: 'Puzzles', Icon: Puzzle },
  { name: 'videogame', label: 'Video games', Icon: Joystick },
  { name: 'fantasy', label: 'Fantasy', Icon: Wand2 },
  { name: 'mystery', label: 'Mystery', Icon: Ghost },
  { name: 'gem', label: 'Treasure', Icon: Gem },

  /* food */
  { name: 'pizza', label: 'Pizza', Icon: Pizza },
  { name: 'bakery', label: 'Baking', Icon: Croissant },
  { name: 'sweets', label: 'Sweets', Icon: Cookie },
  { name: 'party', label: 'Party', Icon: Cake },
  { name: 'healthy', label: 'Healthy food', Icon: Apple },
  { name: 'gardenfood', label: 'Gardening', Icon: Carrot },
  { name: 'icecream', label: 'Ice cream', Icon: IceCreamCone },

  /* animals & nature */
  { name: 'bird', label: 'Birds', Icon: Bird },
  { name: 'cat', label: 'Cats', Icon: Cat },
  { name: 'dog', label: 'Dogs', Icon: Dog },
  { name: 'rabbit', label: 'Rabbits', Icon: Rabbit },
  { name: 'turtle', label: 'Turtles', Icon: Turtle },
  { name: 'squirrel', label: 'Wildlife', Icon: Squirrel },
  { name: 'fish', label: 'Marine life', Icon: Fish },
  { name: 'bee', label: 'Insects', Icon: Bug },
  { name: 'flower', label: 'Flowers', Icon: Flower2 },
  { name: 'tree', label: 'Trees', Icon: TreePine },
  { name: 'planting', label: 'Plants', Icon: Sprout },
  { name: 'weather', label: 'Weather', Icon: Cloud },
  { name: 'sky', label: 'Sky', Icon: Rainbow },
  { name: 'winter', label: 'Winter', Icon: Snowflake },
  { name: 'beach', label: 'Beach', Icon: Palmtree },
  { name: 'camping', label: 'Camping', Icon: Tent },
  { name: 'sun', label: 'Summer', Icon: Sun },
  { name: 'moon', label: 'Night sky', Icon: Moon },

  /* travel & places */
  { name: 'anchor', label: 'Sailing', Icon: Anchor },
  { name: 'ship', label: 'Ships', Icon: Ship },
  { name: 'sailboat', label: 'Boats', Icon: Sailboat },
  { name: 'plane', label: 'Aviation', Icon: Plane },
  { name: 'car', label: 'Cars', Icon: Car },
  { name: 'bus', label: 'Bus trips', Icon: Bus },
  { name: 'train', label: 'Trains', Icon: TrainFront },
  { name: 'worldtravel', label: 'Travel', Icon: Map },
  { name: 'compass', label: 'Orienteering', Icon: Compass },
  { name: 'heritage', label: 'Heritage', Icon: Landmark },
  { name: 'castle', label: 'Castles', Icon: Castle },

  /* science & making */
  { name: 'astronomy', label: 'Astronomy', Icon: Telescope },
  { name: 'micro', label: 'Microscopy', Icon: Microscope },
  { name: 'chemistry', label: 'Chemistry', Icon: FlaskConical },
  { name: 'lab', label: 'Lab work', Icon: TestTube },
  { name: 'physics', label: 'Physics', Icon: Atom },
  { name: 'biology', label: 'Biology', Icon: Dna },
  { name: 'math', label: 'Math', Icon: Calculator },
  { name: 'robotics', label: 'Robotics', Icon: Bot },
  { name: 'invent', label: 'Invention', Icon: Key },

  /* people & life */
  { name: 'kids', label: 'Kids', Icon: Baby },
  { name: 'smile', label: 'Happiness', Icon: Smile },
  { name: 'giving', label: 'Giving', Icon: Gift },
  { name: 'broadcast', label: 'Announcements', Icon: Megaphone },
  { name: 'sound', label: 'Sound', Icon: Speaker },
  { name: 'stories', label: 'Stories', Icon: Feather },
  { name: 'kindness', label: 'Kindness', Icon: Hand },
  { name: 'reading', label: 'Reading', Icon: BookMarked },
  { name: 'business', label: 'Business', Icon: Briefcase },
  { name: 'study', label: 'Study skills', Icon: GraduationCap },
  { name: 'time', label: 'Time management', Icon: Watch },
  { name: 'care', label: 'Care', Icon: HeartHandshake },
  { name: 'cozy', label: 'Cozy club', Icon: Lamp },
  { name: 'expo', label: 'Expo', Icon: Flag },
]

export function clubIcon(name?: string): IconChoice | null {
  if (!name) return null
  return CLUB_ICONS.find((i) => i.name === name) || null
}
